### ISSUE TITLE
Roles/Permissions features

### ISSUE THREAD

**Issue by benaduggan** [keratin/authn-server#10]
Are y'all planning to add some sort of permission/role based system into the mix? Or would you expect the people using this microservice to keep track of emails/permissions for authorization type functionality?

**Comment by cainlevy** [comment]
I'm deferring authorization decisions to the main app, or another microservice if such exists. I don't have strong enough opinions about authorization schemes to tackle that yet.

But if there's anything that AuthN can do to integrate nicely with authorization layers, that may be in scope and I'd love to learn more.

**Comment by rafamel** [comment]
Since a couple years have gone by, are there any further thoughts on this? It would be really nice to manage roles via AuthN without adding an extra layer, or otherwise have an external go-to solution that works nicely w/ it.

**Comment by cainlevy** [comment]
You might be interested in Open Policy Agent as mentioned in #111
