### ISSUE TITLE
Include gosec check in CI

### ISSUE THREAD

**Issue by mohammed90** [keratin/authn-server#102]
The [gosec project](https://github.com/securego/gosec) scans Go project for insecure code. Given the nature of this project, I think it'd beneficial to include such check and including it is trivial.

I did a trial run locally and the reports, so far, seem to be of low-severity (e.g. ignored errors in some writes.). I can work on this, if accepted, after the gRPC work.

**Comment by cainlevy** [comment]
Sounds good to me. I expect the noise rate to be somewhat high, but worth sorting through.

**Comment by AlexCuse** [comment]
@cainlevy opened a PR to get started with this.  There was some noise with default linters so I just added gosec but I think that will be a good start - easy to add in one at a time from there fixing issues as added.

Once we have a strategy we like could add to CI etc but just having the tooling locally seems good for now.
