### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by richardartoul** [keratin/authn-server#11]
Does this support the use-case where users signup / login via 3rd party OAuth (I.E Github / Facebook) ?

**Comment by cainlevy** [comment]
It's planned! 🎉

I'll be sure to update this issue with further developments.

**Comment by sathiyaseelan** [comment]
Is anyone working on this? I can submit a patch for this @cainlevy

**Comment by cainlevy** [comment]
@sathiyaseelan I started sketching some code for this but needed to prioritize some other things. What's your take on how this should be added? My thinking is that the OAuth implementation should result in AuthN issuing a standard id token so the host application isn't forced to care about the differences.

**Comment by sathiyaseelan** [comment]
Yeah. OAuth Callback will return a standard id token but instead of in the json_body it will return as a cookie and redirect to the home page of the application(which we can get from the OAuth login request and keep it in the session).

**Comment by cainlevy** [comment]
Would you mind writing this as a sequence of HTTP calls between the client, host app, AuthN server, and OAuth provider? I'm missing something and I'm not sure where.

(Seems valuable to work this out before investing time in a patch.)

**Comment by cainlevy** [comment]
A few items that I don't want to forget:

## Basic Functionality

* must hide oauth details from frontend and establish a standard authn session
* must support creating new authn account
* must allow attaching oauth identity to existing authn account

## Security Notes

* must not allow access to locked accounts
* data must be deleted when archiving accounts
* must not allow account takeover

## Later Requirements:

* importing oauth data during app->authn migration
* fetching oauth token for application use
* specifying extra token scopes for application use

**Comment by k1ng440** [comment]
status please?

**Comment by k1ng440** [comment]
https://www.ory.sh/

**Comment by cainlevy** [comment]
Almost code complete, maybe tomorrow? Next steps are to write a demo integration and a bit of documentation. If anyone is interested in providing feedback on the implementation during a pre-release, let me know.

**Comment by k1ng440** [comment]
count me in.

**Comment by k1ng440** [comment]
i think you should implement https://github.com/golang/oauth2

**Comment by cainlevy** [comment]
Yep, that's what the pull request implements.
