### ISSUE TITLE
How to authorize users?

### ISSUE THREAD

**Issue by Mseller** [keratin/authn-server#114]
# How to authorize users?
I have been researching for a while on how to authorize users in a micro-service architecture and all seem to use extra claims in the JWT token, however since I am using authn-server (which is awsume btw!) that option is not available to me, so now i look to you who also use this framework to see how you have solved it.
# Background
What I am trying to do is to build a frontend with multiple micro-services in the backend. What I was thinking I would do is to use an api-gateway which would be responsible for authenticating the users and then forward the request to the correct micro-service.

# Problem
Okey, so for one given that the user is logged out and requests to login; the gateway would the make a request to the authn-server service which would take the credentials and pass back a JWT token. Then the user request a resource say, for example, a salary page (which not all users should be able to see) the request would then go through the gateway which would first ensure the JWT token is valid then retrieve the users' permissions and forward the request to the correct service. Then the first problem is, where do I store the permissions in the request? I could create a custom header say "x-permissions" and pass that along with the request. However, this creates the problem that I would then for every request the user does to the backend have to retrieve the users' permissions from the users' service, populate the header and then forward the request. Would it be possible to store this information client side somehow? I do recognize that if this information is to be stored at the client, it needs to be signed somehow as to not be tampered with. If that is the case how could one go about doing that?
Since if this information could be stored client since, I would only have to populate that information once when the user authenticates, eliminating a lot of requests to the users' service.

Is there any better way of approaching authorization? I would appreciate it greatly if you could give me any pointers or show me some resources where I could further research this.

**Comment by cainlevy** [comment]
⚠️  This is a single perspective, and describes a pattern that I haven't yet deployed. I work with a monolith. ⚠️ 

I'd break your problem down into two pieces and solve each independently.

1) How do you pass information from the gateway to your services? Do you use headers or some other structured object? Does the connection between the gateway and the services need to be tamper-proof (signed)?

    AuthN doesn't have much to say here. Some ideas:

    * Your gateway could unpack and verify the identity token and forward only the userID to your microservices.
    * Your gateway could forward the whole identity token to your microservices and expect them to verify.
    * Your gateway could create its own JWT from aggregated data (identity + roles) and pass it to your microservices.

2) How much efficiency do you need?

    * Can you afford to look up user information on each request? 
    * Can you get away with a simple LRU cache in the gateway?
    * Can you store the data in the client?

    If you decide to store the data in the client, you're not strictly limited to AuthN's JWT. You could devise a companion JWT that must match AuthN's `iat` and `sub` claims in order to be accepted. If it does not exist, create and sign it (probably using HMAC).

**Comment by silasdavis** [comment]
What we have done/are doing is to implement some endpoints that support an OIDC provider Ory Hydra - referenced here: #124

Hydra issues access tokens for our other services and we just use keratin's refresh token for first-party access to the global user account. Hydra handles the various audiences and scopes via the OpenID connect standard and some configuration.

This might be overkill if you do not want to act as an OpenID provider, but we decided it killed two birds with one stone for us... 

The other way we consider was using the envoy proxy to authenticate and pass requests along: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto

I believe you can implement some of the suggestions @cainlevy makes above which seem sensible to me. It looked like it would be fairly clean.
