### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by rrjanbiah** [keratin/authn-server#130]
I understand that this library is licensed under LGPL. But, I read so many explanations about LGPL with respect to microservices, etc. So, thought of directly checking with the author @cainlevy on what restrictions you wanted to be obliged in a commercial software that uses your library? Similarly, what restrictions you wanted to be obliged in other open source licensed software?

**Comment by cainlevy** [comment]
Hi @rrjanbiah, thanks for asking!

Quick clarification: I do not intend for the LGPL license to have any impact on using AuthN as a microservice. I do not consider API usage to be "combining or linking".

## commercial projects

If a commercial project uses AuthN as a microservice, they're welcome to deploy it and contribute back to it just like anyone else. Everyone needs authentication!

If a commercial project bundles and sells AuthN+Whatever, then I want AuthN's license to require that they negotiate with me. If there's any doubt about the difference between using and bundling/selling, please reach out with specifics and I can offer some kind of written signoff.

## open source projects

If the open source community builds new open source software that works well with AuthN, that's awesome. I'd like to hear about it and promote it.

If the open source community builds new open source software by bundling and redistributing AuthN, that's cool too. I'm happy that AuthN can be a useful building block. I would expect that the same commercial restrictions mentioned above would apply to this new project.

## LGPL

Does the LGPL accomplish everything I described above? I really don't know. If someone with more licensing knowledge comes across this issue and can provide insight and suggestions, I'm ready to listen.

**Comment by rrjanbiah** [comment]
@cainlevy Thanks a lot for your explanation. 

I'm not an expert in licensing. But, I see number of open source libraries relicensing to non-GPL variants as there are many discussions on companies are wary of GPL variants and avoiding them.
