### ISSUE TITLE
Question: Disable signup-endpoint

### ISSUE THREAD

**Issue by ppacher** [keratin/authn-server#135]
Hi,
is it possible to just disable the signup endpoint? I'd like to use authn-server but without a public signup. I know I can route everything through an application gateway but this requires to ensure that all other routes are correctly forwarded and I'd like to terminate TLS just before the authn-server. 

All users would be created by "administrators" using the private ImportAccount endpoint (or the signup endpoint if I can configure it to be "private").
Thanks in advance

**Comment by Mohammed90** [comment]
Set the `ENABLE_SIGNUP` env var to false

https://github.com/keratin/authn-server/blob/master/app/config.go#L212

**Comment by ppacher** [comment]
Awesome thanks! Seems this one is missing in the documentation.
