### ISSUE TITLE
Is AuthN prod-ready ?

### ISSUE THREAD

**Issue by lnalex** [keratin/authn-server#141]
Hi,

I'm looking for a good passwordless authentication module for our startup to be used in production environment with an existing PG database.

Are there any that use AuthN in production today? Is it mature enough compared to the most established Keycloak ?

Thanks !

**Comment by cainlevy** [comment]
Yes, AuthN is production ready. I've been using it in a project for a few years. I believe others have as well, but I don't have that visibility.

Keycloak has some different characteristics, but I don't have a full feature comparison to offer. It wasn't on my radar when initially developing AuthN.
