### ISSUE TITLE
AuthN does not parse JSON requests

### ISSUE THREAD

**Issue by cainlevy** [keratin/authn-server#143]
AuthN does not parse requests with `Content-Type: application/json`. This can be a hurdle to getting started for folks testing the server directly without the aid of a client library.

**Comment by martinreus** [comment]
Regarding this issue: should the API effectively change to support both or just application/json?

Do you already have a rough idea in mind on how to implement this?

**Comment by cainlevy** [comment]
I envision the API supporting both, with a Content-Type aware wrapper for reading a form param.

**Comment by martinreus** [comment]
cool, I'll try to help with this one :)
