### ISSUE TITLE
Release new binaries

### ISSUE THREAD

**Issue by egorsmkv** [keratin/authn-server#148]
Hi, @cainlevy 

Can you release new builds, please? Especially for Windows.

**Comment by cainlevy** [comment]
https://github.com/keratin/authn-server/releases/tag/v1.8.0

**Comment by egorsmkv** [comment]
Thanks, Lance!

**Comment by egorsmkv** [comment]
By the way, I have made a log in/sign up application using Windows Forms and AuthN.

![Capture](https://user-images.githubusercontent.com/7875085/73797363-b5987700-47a7-11ea-9f81-ca8cba145621.PNG)
