### ISSUE TITLE
Helm charts for keratin

### ISSUE THREAD

**Issue by obukhov** [keratin/authn-server#151]
Hello @cainlevy 

Thank you for all your work. I wanted to experiment with keratin and potentially use keratin in my hobby projects. I use terraform and helm to configure my playground and I was a bit upset to know that there are no helm charts available for it. I also wanted to learn about helm a bit more so I created charts for helm version 2 and 3 here: https://github.com/obukhov/keratin-helm-charts

I tested them and they seem to work although there is probably plenty of space for improvements. I created helm repo with github pages, so potentially anyone can use it: https://github.com/obukhov/keratin-helm-repo

I was considering to create a PR to add by repo to helm hub (like described here: https://github.com/helm/hub/blob/master/Repositories.md). But before that, I wanted to discuss with you the following question:  I think it would make much more sense if these two repos will be moved to keratin organization - it will be easier to discover them and contribute for the others and also help to get rid of "bus factor". 

I also haven't used any keratin related images in the charts (like icon/logo)  because I wasn't sure this is allowed.

Let me know what you think about that.

**Comment by cainlevy** [comment]
@obukhov Thanks for publishing those! I'd love to reference them in the docs, if you're willing to do a short writeup.

I'm also happy to host the repos under the keratin organization. We'll just want to include the standard code of conduct, I think. Are you willing to remain as a maintainer? I'm not using k8s currently so it's outside of my expertise.

**Comment by obukhov** [comment]
Yeah I would be happy to maintain these two repos within the organisation as I have plans for future improvements. I would also reorganize naming a bit to get rid of prefix which will not be needed if the repo is under organisation. So I'll prepare repositories content and try to transfer them

**Comment by obukhov** [comment]
Hi! Tried to move one of the repos today, but got an error:
```
You don’t have the permission to create public repositories on keratin
```

I see two possible options:
- you can add me to org and grant permission to create public repos
- you create  public repos and grant me full control over them (do not initialize them with any files in that case)

If you prefer 2nd option then the names of repositories I planned to move are:
- helm-repo
- helm-charts

The first one is for packaged charts (distributed through GitHub Pages) and the second one for source charts. Please enable GitHub Pages for the first one with an option "for master branch".

**Comment by cainlevy** [comment]
I've created the repos and invited you, but I'm unable to set up GitHub Pages while the repos are empty. Let me know if I can offer any more assistance, and thanks for contributing!

**Comment by obukhov** [comment]
Sorry, it didn't work out:
```
> cat .git/config                             
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:keratin/helm-charts.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "helm2-compatible-chart"]
	remote = origin
	merge = refs/heads/helm2-compatible-chart

> git push
ERROR: Permission to keratin/helm-charts.git denied to obukhov.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Maybe then it is better to follow plan a? 
Or you can checkout my repos, change origin and push. 
Or you can just fork my repos into the organisation and I delete them in my account. 
Links are:
- https://github.com/obukhov/helm-repo
- https://github.com/obukhov/helm-charts

**Comment by cainlevy** [comment]
When you visit the repos do you see invitation to join? I'm not sure what the UI is like but GitHub suggests these URLs could help:

https://github.com/keratin/helm-repo/invitations
https://github.com/keratin/helm-charts/invitations

**Comment by obukhov** [comment]
Yeah, that worked
