### ISSUE TITLE
Do not allow a session refresh if the account has changed their password

### ISSUE THREAD

**Issue by nathanpalmer** [keratin/authn-server#153]
Something we've been discussing internally is to invalidate all sessions when someone changes their password. Is there a way to do this? and would it be a reasonable default?

**Comment by cainlevy** [comment]
Yes there is a way to do this. AuthN will already expire the refresh token in other circumstances, so it's just a matter of exposing the functionality in a new place. Would you expect to see this as an option for the change password API or as a separate (composable) API?

**Comment by nathanpalmer** [comment]
I would see this as more of a system-wide option that is either there by default, or could be enabled via an environment variable. Given that the change password API is called via the front-end and that may or may not always be 100% followed if it's an option there, and I see this as more of a system-wide security setting.

**Comment by cainlevy** [comment]
Interesting, I hadn't considered it as a system-wide security setting. I was recalling device management pages with "log out all" buttons.

Suppose for a moment that enabling this behavior was a responsibility of the frontend. If someone made a modified API call to avoid logging out all other devices, they'd likely know and accept the consequences. If they weren't aware of the consequences, then the modified API call might be XSS with more dangerous outcomes.

It's tough to know how conservative to be here. I want AuthN to promote security best practices while still offering as much usability as possible within those constraints.

**Comment by nathanpalmer** [comment]
It seems the security recommendation from OWASP is to invalidate all sessions

![image](https://user-images.githubusercontent.com/125599/76778766-bea23e00-6780-11ea-8076-f3302f58be00.png)

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Forgot_Password_Cheat_Sheet.md

However, [a StackExchange security expert seems to think otherwise](https://security.stackexchange.com/questions/63256/on-password-change-in-a-web-application-should-it-log-out-all-other-sessions?noredirect=1&lq=1). I'm not sure their reasoning is sound though, when they state an attacker would log out your session when that happens and you should have a "log other sessions out". Having a second step simply is 1 extra click for the attacker and would be very likely the thing they'd have on their mind to do if they were trying to take over the account.

In terms of implementation, if you don't want to force this on people, could either be
- backend environment variable (on or off)
- OR extra parameter to the password reset

I prefer making it global, but we control our front-ends so either way is fine. (We just have 4-5 front-ends to change.. not to mention we're on an older version of the server.)

**Comment by cainlevy** [comment]
Thanks for surfacing that OWASP recommendation.

My plan at this time is to make a server variable that defaults to off until some future 2.x release creates an opportunity to change default behavior.

Feel free to reach out if you have questions about catching up on server versions. I've tried to keep AuthN backwards compatible but there have been a couple of database migrations.

**Comment by nathanpalmer** [comment]
Great, thanks!
