### ISSUE TITLE
More flexible domain restrictions

### ISSUE THREAD

**Issue by zekenie** [keratin/authn-server#156]
It would be wonderful if we could use wildcards in the `APP_DOMAINS` environment variable. We are trying to enable staging deploys for each pull request to our frontend. These frontends all point to the same backend staging server and authn instance. I'd love `pr-*.ourdomain.com` to be allowed to make requests to authn.

**Comment by cainlevy** [comment]
This looks quite achievable. I think nearly all of the functionality could be built into one function:

https://github.com/keratin/authn-server/blob/e1b22d8acc39b2ec618136792f53c76c1c7790c2/lib/route/domain.go#L39-L63

That should enable CORS and the Origin validation to work. The remaining bit that I've found is a failsafe return URL for OAuth:

https://github.com/keratin/authn-server/blob/e1b22d8acc39b2ec618136792f53c76c1c7790c2/server/handlers/get_oauth.go#L19-L26

This code path isn't expected though, unless something is misconfigured or a user is messing around with URLs. A simple word of advice in the documentation to maintain a non-wildcard domain in first position should be enough.

@zekenie Is this something you're interested in implementing?

**Comment by zekenie** [comment]
@cainlevy I'd love to. Unfortunately I've never touched go before, so I'm a bit concerned I'll get stuck on simple stuff. I might give it a try this weekend. If I can't figure it out, I'll just enthusiastically cheer from the sidelines in the hopes that you or someone else picks it up
