### ISSUE TITLE
AccountStore in PostgreSQL

### ISSUE THREAD

**Issue by cainlevy** [keratin/authn-server#16]
* Manage dev dependency through docker-compose
* Add accounts table migration
* Add AccountStore implementation (probably a near-copy of MySQL + Sqlite)
* Add to existing AccountStore tests

**Comment by shashankmehra** [comment]
Can you elaborate on `Manage dev dependency through docker-compose`?
Currently docker-compose sets up a MySQL database but the `authn` container uses sqlite.

**Comment by cainlevy** [comment]
The `make test` command sets a `TEST_MYSQL_URL` environment variable matching the `docker-compose` config. Then, the `mysql.TestDB()` func reads that config to establish a connection during `data/account_store_test.go`.

**Comment by sathiyaseelan** [comment]
Is anyone already working on this? Or shall I take it up?
