### ISSUE TITLE
Feels a bit slow?

### ISSUE THREAD

**Issue by saul-gush** [keratin/authn-server#161]
Maybe it is the way I have set this up but it feels a bit slow. I did some testing from a pod in the Kubernetes cluster and checking if a user already exists on register varies between 300ms and as high as 2 seconds. That feels very slow for a Go application. 

![image](https://user-images.githubusercontent.com/63714857/86543169-00174e80-bf14-11ea-8826-ef802ccb6a56.png)

**Comment by saul-gush** [comment]
Login as well...

![image](https://user-images.githubusercontent.com/63714857/86543387-dfe88f00-bf15-11ea-842e-48a0acf1b92c.png)

**Comment by cainlevy** [comment]
Yeah that's incredibly slow. Checking a username is a single query.

**Comment by saul-gush** [comment]
Are you seeing the same on your side?

**Comment by cainlevy** [comment]
I'm getting 0.1s response times against a local AuthN instance, and 1.0s against an instance in AWS Fargate (including 0.13s connection time).

**Comment by saul-gush** [comment]
Fargate may not be the best to test against, as there may be warm up time.
Docker on VM probs better.

I’m speculating here but I’m thinking maybe how the database connection is
being handled. Does it connect on every request and then close or is the
connection open as a variable to the whole server while running.

Ill go through some of the Authn code later on, see if I can see anything
on that front. I have some high performance code that I can share as an
example and how we deal with database connections.

We use Go Fiber with Gorm and it’s super fast, typically response times
between 1ms and 6ms.

**Comment by cainlevy** [comment]
I believe that Fargate instance was warmed up, but your point is well taken.

I'm excited to hear what you find.

**Comment by saul-gush** [comment]
I tested for the database connection and its not that. 

I added in some pprof into public_routes.go - It has something to do with Blowfish keeps running, even on a registration and the user already exists? Login speed is also super slow, not sure why. 

I really want to check speed on the API that unpacks/validates JWT tokens - that is the critical one. As I want to use it in my API gateway. I will be raising a separate ticket on that btw - we are trying to figure that out using go client and the jwt keys. 

```golang
	route.Get("/debug/pprof/").SecuredWith(route.Unsecured()).Handle(handlers.Index(app)),
	route.Get("/debug/pprof/cmdline").SecuredWith(route.Unsecured()).Handle(handlers.Cmdline(app)),
	route.Get("/debug/pprof/profile").SecuredWith(route.Unsecured()).Handle(handlers.Profile(app)),
	route.Get("/debug/pprof/symbol").SecuredWith(route.Unsecured()).Handle(handlers.Symbol(app)),
	route.Get("/debug/pprof/trace").SecuredWith(route.Unsecured()).Handle(handlers.Trace(app)),
```

The below is all running locally 

User already exists (440ms)
![image](https://user-images.githubusercontent.com/63714857/86622462-d1eb4a80-bfb7-11ea-9915-ac036500eba8.png)

![image](https://user-images.githubusercontent.com/63714857/86622527-e891a180-bfb7-11ea-9977-93b4dee405e6.png)

User login (1.23 seconds)
![image](https://user-images.githubusercontent.com/63714857/86622568-ffd08f00-bfb7-11ea-98e0-77a1a8e53e3a.png)

**Comment by cainlevy** [comment]
I think I've found an explanation. It's likely confusion around the uniqueness validation.

The `POST /accounts` endpoint doesn't check for uniqueness before it attempts to insert. This is an optimization for the common case where the user submits a unique username. The result is the password must be hashed anyway, so yes, bcrypt clock time is normal. You should see a significantly faster failure by submitting a missing password or username.

Maybe your VM is underpowered? You might adjust the bcrypt cost with [`BCRYPT_COST`](https://keratin.github.io/authn-server/#/config?id=bcrypt_cost) if it's not a production environment.

**Comment by saul-gush** [comment]
All of these tests were done on Macbook Pro (2018) without a VM or docker. I ran Go directly with environment variables. One of the tests was an existing user on registration, certainly shouldn't be 400ms. Over 1 second for login is nuts. Sometimes got as high as 3 seconds. I havent experienced anything close to this with other authentication providers. We currently implemented one of the bloated java solutions which requires over 1GB of memory in dev! Sadly I am gravitating away from Keratin AuthN, these arent problems I want to be solving. I was hoping to see better performance with a lightweight solution for Kubernetes - Im just not seeing it. I think there is a real gap in that space in the market - Kratos could be an option but its stupid complex to setup and in alpha stage.

**Comment by cainlevy** [comment]
All I can say is that your pprof results show all of the time spent in blowfish. That's the password hashing. It's intended to be expensive, and it runs even when the username is already taken. If you'd like to understand and isolate the problem, try playing with `BCRYPT_COST`, testing a different kind of validation failure, or gathering timing results from the health check endpoint.
