### ISSUE TITLE
Contribution: Node.js Backend Client

### ISSUE THREAD

**Issue by bradenmacdonald** [keratin/authn-server#162]
Hey, thanks for this great microservice. I made a backend API client for Node.js: https://github.com/bradenmacdonald/authn-node

The Node.js app I'm using it with isn't in production yet, but everything seems to work well in my dev/staging environments.

Let me know if you mind me publishing it on npm as `authn-node`, or if you'd like to do that. If you want to move it into the `keratin` GitHub org, that's fine with me too.

**Comment by cainlevy** [comment]
That's great!

I'm feeling quite sheepish right now, because I've recently been using NodeJS and also wrote an integration client. I just checked on it to figure out what happened here and realized it's a private repo. :disappointed: :cry: :sob: 

Would you be interested in collaborating on it for unique functionality that may exist only in your client?

**Comment by cainlevy** [comment]
Fixed the visibility: https://github.com/keratin/authn-node

I've been so busy these past months that I'm not sure if this is being advertised in the proper places.

**Comment by bradenmacdonald** [comment]
Argh, too bad. Thankfully I didn't invest too much time in this, it's just a small API client. Thanks for making yours public! Would you mind adding a link it to this README too? https://github.com/keratin/authn-server/blob/master/README.md#related

> Would you be interested in collaborating on it for unique functionality that may exist only in your client?

Sure, though I think they're pretty similar. From a glance the only thing I see in mine but not yours are `requestPasswordlessLogin` and `isUsernameRegistered` which I found useful to have available to the backend as well as the frontend.

**Comment by cainlevy** [comment]
> the API client I ended up with has only 3 total dependencies

Makes sense to me.

This was written for Ruby but it's probably still relevant to NodeJS: https://www.mikeperham.com/2016/02/09/kill-your-dependencies/

**Comment by cainlevy** [comment]
@bradenmacdonald consider this a standing offer to collaborate on the keratin/authn-node repo if your dependency constraints  change!
