### ISSUE TITLE
Bug: Passwordless login token generation fails when the username includes a plus / "+" sign 

### ISSUE THREAD

**Issue by drevets** [keratin/authn-server#164]
Steps to reproduce: 
- Follow instructions for implementing the [passwordless login flow](https://keratin.github.io/authn-server/#/guide-implementing_passwordless_logins) by implementing an APP_PASSWORDLESS_TOKEN_URL and configuring AuthN instance with it. 
- After requesting a passwordless login token by calling /session/token with a valid username (that includes a "+"), there will be no POST request to the webhook 
- Calls with usernames that include other characters (_, -, and .) succeed 

Additional notes: 
- In our config, we have `USERNAME_IS_EMAIL=true`
- We found this behavior in dev, staging, and prod environments 
- Our keratin version is from this docker image `keratin/authn-server:1.10.2`

**Comment by cainlevy** [comment]
Thanks for the report! I'll take a look.

**Comment by cainlevy** [comment]
I haven't found anything obvious yet. My best guess is that the request is missing url encoding and looks like `GET /session/token?username=foo+bar@example.com` when it should be `GET /session/token?username=foo%2Bbar%40example.com`.

Are you using authn-js to make the request on `/session/token`? What version?

Might you share an example HTTP request?

**Comment by drevets** [comment]
I think that was probably the issue!! 🤦🏻‍♀️

Here's an example request from docker logs: `dev_authn_1   [17/Dec/2020:15:54:05 +0000] "GET /session/token?username=emily+1@foobar.com HTTP/1.1" 200 0 "" "axios/0.19.2"`

We are sending the request on `/session/token` with axios. here's the method where we make the call:

```public async requestPasswordlessLogin(email: string) {
    try {
      const res = await this.httpService
        .get(
          `${this.config.get<string>(
            "AUTHN_URL"
          )}/session/token?username=${email}`,
          {
            auth: {
              username: this.config.get<string>("AUTHN_ADMIN_USER"),
              password: this.config.get<string>("AUTHN_ADMIN_PASSWORD")
            },
            headers: {
              "content-type": "application/x-www-form-urlencoded",
              origin: this.config.get<string>("API_URL")
            }
          }
        )
        .toPromise();
    } catch (e) {
      Logger.error(`error from authn ${JSON.stringify(e.response.data)}`);
      throw new InternalServerErrorException();
    }
  }```

**Comment by cainlevy** [comment]
Indeed! Add some url encoding and I think you'll be back to normal.
