### ISSUE TITLE
Verifying user is logged in

### ISSUE THREAD

**Issue by pdavis156879** [keratin/authn-server#166]
Full disclosure - I'm fairly new to web development and Go

I'm developing a Go Gin REST API and I stumbled upon AuthN which is marvelous since I was struggling with developing my own auth service.

My question is: how can I validate if a user is actually logged into AuthN without forcing him to login otherwise? That is, simply validating if the OAuth JWT token is set and valid (sorry again, I'm not exactly proficient in these terms)

Thank you!

**Comment by pdavis156879** [comment]
Just noticed this can be achieved using  `SubjectFrom`, if an error is returned then the user is not authenticated.

**Comment by cainlevy** [comment]
Yes, `SubjectFrom` is the best way to verify that a user is logged in from your backend app. This returns an AuthN account ID, which should be saved with your user record so you can easily associate the two.

From the client (e.g. browser) you can also check that a user is logged in by requesting a new ID token. This will only work when the user is logged in. The server documentation is here: https://keratin.github.io/authn-server/#/api?id=refresh-session, and the authn-js documentation is here: https://github.com/keratin/authn-js/#api.
