### ISSUE TITLE
Support for Redis Sentinel

### ISSUE THREAD

**Issue by conanca** [keratin/authn-server#172]
REDIS_URL set with

redis-sentinel :// [[username :] password@] host1[: port1] [, host2[: port2]] [, hostN[: portN]] [/ database][?[timeout=timeout[d|h|m|s|ms|us|ns]] [&_sentinelMasterId=sentinelMasterId_] [&_database=database_]]

got error "redis.New: invalid redis URL scheme: redis-sentinel"

**Comment by cainlevy** [comment]
@conanca Is this something you're interested in contributing?

It looks like the redis client currently packaged by authn-server supports Redis Sentinel via [`NewFailoverClient`](https://pkg.go.dev/github.com/go-redis/redis/v8#NewFailoverClient). This may require checking the scheme in https://github.com/keratin/authn-server/blob/master/app/data/redis/db.go, or possibly updating the redis module dependency.

**Comment by cainlevy** [comment]
Closed by #181
