### ISSUE TITLE
configuration for setting id-token in cookie

### ISSUE THREAD

**Issue by brietsparks** [keratin/authn-server#182]
I have SSR logic that hydrates the page data based on user-id, so it needs to authenticate the user from the initial request's cookie. 

Currently, my authn-service instance's login and register endpoints return the id-token in the response payload, so I have to set it in localstorage.

Is there a way to configure authn-server so that those endpoints set the id-token in the cookie?

**Comment by cainlevy** [comment]
The reason those two endpoints don't set the ID token as a cookie is because AuthN may not be on the same domain as your main app.

The authn-js client, on the other hand, has a cookie storage option that might work for you. What do you think?
