### ISSUE TITLE
GET /password/reset documentation is ambiguous

### ISSUE THREAD

**Issue by alee792** [keratin/authn-server#184]
In the API docs, it's not entirely clear that the requested username should be a query parameter. It's implied, since it is a GET, but given how opaque responses for this request is, it may be useful to be explicit: `password/reset?username=:username`.

~It could also be more explicit that the callback's "request body" is actually query parameters, not a `http.Request.Body`.~

https://keratin.github.io/authn-server/#/api?id=request-password-reset

Edit: sorry, the callback _is_ a form body.

**Comment by jeffreylo** [comment]
Seems like this is resolved?

**Comment by mohammed90** [comment]
GET requests do not have a body, so this is a given. Where is the ambiguity?

**Comment by cainlevy** [comment]
thanks for bumping this issue! i'd let it slip.

perhaps this endpoint could return a 422 status code when the username param is missing. that might have given you more feedback on your integration?

incidentally, it sounds like you may have been creating a custom integration. was https://github.com/keratin/authn-js not suitable?

**Comment by alee792** [comment]
I think @mohammed90 is right. Not sure if I had some other line of thought when I opened the issue originally, but that should be sufficient.

@cainlevy We don't want to expose Keratin as an edge service, nor do we want our UX to interact directly with its API. Instead, we have a backend-for-frontend API that's more attuned to our requirements.
