### ISSUE TITLE
Non-default Redis user does not work due to outdated version of go-redis library 

### ISSUE THREAD

**Issue by Probotect0r** [keratin/authn-server#186]
I am trying to run an AuthN Server that is backed by an AWS Elasticache Redis instance. I have created two different  Elasticache Users, which map directly to Redis ACL users. One of the users is `default`, and the other is `user1`.

When I set `REDIS_URL` to `redis://user1:password@myhost:myport`, I am not able to authenticate. When I use `redis://default:password@myhost:myport` or `redis://:password@myhost:myport`, it works correctly. 

Digging into the underlying `go-redis` library (version 6.15.2 as used by this module), It seems like the username is ignored entirely, as seen here: https://github.com/go-redis/redis/blob/v6.15.2/options.go#L174-L179. But, starting with V8 of the library, Username is not ignored: https://github.com/go-redis/redis/blob/v8.0.0/options.go#L201-L206.

Are there any plans on upgrading the `go-redis` library to 8.0 or above? It would be nice to be able to use a non-default Redis user. 

Thanks

**Comment by cainlevy** [comment]
I agree, that's a good reason to update the dependency.
