### ISSUE TITLE
FEATURE IDEA: Account Invite API

### ISSUE THREAD

**Issue by xcskier56** [keratin/authn-server#188]
### Idea
We'd like the ability to have our server side application send newly created accounts an email to create a password. This is 99% the same as a reset password flow, except that 1) it is triggered by our server and 2) we need to send a different email which means we need the AuthN server to hit a slightly different endpoint than reset password

### Changes API
1. Create a new **private** endpoint that behaves identically to the current reset password endpoint. Potentially `/account/invite`
2. Add a new env var `APP_INVITE_URL` that would be the uri of the server to call to deliver the a "invite" aka reset password token

Thoughts/Feedback?

Thanks,

Doug

**Comment by xcskier56** [comment]
@cainlevy pinging. Would like to hear your thoughts & openness to this feature. Thanks!

**Comment by cainlevy** [comment]
Thanks for the bump!

Some time ago I imagined an application that wanted to use invitation codes and wrote down some notes on how it might be done. Do you have any feedback on how coherent / realistic / possible / applicable the notes are in your situation?

https://keratin.github.io/authn-server/#/guide-restrict_signups_by_invitation

**Comment by cainlevy** [comment]
I really should clarify.

I'm imagining that you have open signups but also want users to be able to invite others to join. Your envisioned steps might be:

1. user submits email they would like to invite
2. backend creates authn account
3. backend asks authn for a reset token
4. authn generates a reset token and submits it back by webhook
5. backend delivers "you've been invited" email to user, containing reset token
6. invited user clicks through email to landing page
7. invited user supplies a new password
8. frontend submits new password to authn as a normal reset

My question is why you need the account to exist in AuthN prior to the invited user arriving. Is it to verify that they really were invited, or to satisfy a database constraint on not-null `account_id`?

**Comment by xcskier56** [comment]
Thanks for the reply, I feel a little dumb that I forgot about that page in the docs. I read it a long time ago when we were first integrating but totally forgot about it. The flow you laid out in your 2nd message is exactly what we've done in the past and what I had in mind when I opened this issue.

Our use case is for a closed application that only pre-authorized accounts are allowed to sign up for. Right now I have a script to manually create & import the accounts with a random password (`SecureRandom.hex(18)`) and then we send them a password reset to give them access to their account. 

I'll say that we do not absolutely need the account to exist in AuthN, but we do have a `null: false` constraint on that column. To me, the bigger issue is that to accomplish this flow, we need to have open signup which in this application I'd like to avoid. 

The final reason I'm interested in this flow if that it puts more of the work into the auth system and allows the application to do less... to be fair we're "overloading" a feature that wasn't meant to do this, but yeah.

**Comment by cainlevy** [comment]
You make a good point about allowing the application to do less. I'll think it over.

In the meantime, I'm thinking back to:

> 2) we need to send a different email which means we need the AuthN server to hit a slightly different endpoint than reset password

Is it possible for your application to overload the password reset process and recognize when the account has not finished signup? If that were possible, is there anything you'd still want from AuthN?

On reflection I might suggest that it's already valuable for your application to distinguish between provisional and complete accounts. Provisional accounts shouldn't get email notifications and may not be legally bound by your ToS.

**Comment by xcskier56** [comment]
Great idea on the overload. Thinking about we don't have a way currently to achieve this but could add it and then change the email we send based on that. 

Your point about distinguishing between provisional and complete accounts is well taken and in most situations probably correct. However this is a Saas application and the ToS and other contractual obligations are handled offline en-mass through a different contracting process. 

We're not quite to needing this yet and so will keep thinking on how we can handle on our end

**Comment by cainlevy** [comment]
Happy to re-open as needed.
