### ISSUE TITLE
SSO; single api server, multiple client applications

### ISSUE THREAD

**Issue by jeffreylo** [keratin/authn-server#193]
The audience (`aud`) in the identity/access token contains only the requesting origin (and only if it’s an authorised origin per `APP_DOMAINS`). 

If I have a `n` API servers for multiple clients, e.g., 

```
client1.example.com,client2.example.com => api.example.com
```

This introduces an issue:

1. identity JWTs only contain an `aud` for the requesting domain, e.g., [when a session is created](https://github.com/keratin/authn-server/blob/1895d67d484583a3dfb37dcf5d155283b98e0133/server/handlers/post_account.go#L39-L42) or [refreshed](https://github.com/keratin/authn-server/blob/1895d67d484583a3dfb37dcf5d155283b98e0133/server/handlers/get_session_refresh.go#L22-L25). For example, a jwt for client1.example.com would have `aud=[client1.example.com]`.
2. client libraries for authn-server require an all-of match, but can only be configured to match one audience. For example, authn-go only accepts the single domain of the host application: https://github.com/keratin/authn-go/blob/3913e1540d0aefd29cf4f0111bf5caa4a282671f/authn/config.go#L11. This means that the host application would (potentially) need multiple authn-go clients to validate against `n` potential audiences.

Is one path forward support for `one-of` audience verification, as described in https://github.com/keratin/authn-go/issues/14? If this is better suited as an issue for the client library, e.g., authn-go, happy to file. Let me know.

**Comment by cainlevy** [comment]
Support for `one-of` might be an interesting path forward but I'm also curious whether https://github.com/keratin/authn-go/pull/15 also solves your issue?

One advantage to `SubjectFromWithAudience` is that it doesn't need to be pre-configured with a finite set of audiences at startup.

I'll close this issue on authn-server as it appears to be related to authn-go. Let's continue over there if you think there's more to discover.
