### ISSUE TITLE
/jwks endpoint is not public

### ISSUE THREAD

**Issue by Probotect0r** [keratin/authn-server#197]
The documentation mentions that the `/jwks` endpoint has [Public visibility](https://keratin.github.io/authn-server/#/api?id=json-web-keys), but I am not able to access it on the public API. Only the private API seems to expose it.

I would like to be able to access the `/jwks` endpoint through the public API so that I can verify JWT tokens in my API Gateway.

The `/configuration` endpoint is also specified as being public, but is only available on the private API.

**Comment by cainlevy** [comment]
Makes sense to me! I'd be happy to see it available over both ports. Is this something you're comfortable adding, or would you want assistance?

**Comment by Probotect0r** [comment]
I am not a Go developer, but I can give it a go (pun intended). I'll comment here if I need help.
