### ISSUE TITLE
Access token fails to refresh in Progressive Web App (PWA) on mobile (Android and iOS), with refresh token unexpired

### ISSUE THREAD

**Issue by drevets** [keratin/authn-server#202]
Hi -- 

We've been using Authn (both authn-server and authn-js) for several years. We've discovered an issue (which is frustratingly vague), whereby users on our PWA on mobile find they have to log in _too much_. We had not changed the configuration for either the ACCESS_TOKEN_TTL or the REFRESH_TOKEN_TTL, so my understanding is that users should remain logged in for 30 days, with authn-js automatically attempting to refresh their access token at the half life (which would be every 30 min). 

The refresh attempts appear to be failing with a 401, somewhat reliably, in the PWA after about a day or a period longer than 1 hr -- I'm not exactly certain how long it takes for it to happen as I haven't been able to reliably reproduce the issue. I don't know for sure, but I don't think it matters if the user closes out of the app, or merely minimizes it and uses other applications on their phone. However, I do think that if our PWA were open on their phone, the refresh logic would work, but something about minimizing it or having it go "dormant" seems to cause an issue. 

There was a bit of documentation for the /session/refresh route that potentially seemed relevant: 

```As long as a device remains logged in to the AuthN server, it can hit this endpoint to fetch a fresh JWT session. The [keratin/authn-js](https://github.com/keratin/authn-js) library can automate this by preemptively refreshing tokens when they reach halflife.``` 

Is the mobile device not remaining logged in to the AuthN server and that's causing the problem? If so, is there a way to prevent its disconnection? 

I'm also wondering if this could be an issue related to switching networks or losing connectivity in general, though it seems like AuthN should still be able to refresh the token after losing connectivity, so long as the refresh token were still valid. 

It seems improbable that the refresh tokens themselves are expiring, given they are supposed to be good for 30 days -- so I'm also wondering if there are other reasons for the refresh attempt to fail with a 401 that might have to do with timeouts, etc. 

Versions of AuthN: 

- authn-js: 1.3.0 
- authn-server: 1.10.2

Example of failing request (from logs in Heroku): 
- "GET /session/refresh HTTP/1.1" 401 0 "https://frank-staging.netlify.app/home" "Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1"

**Comment by cainlevy** [comment]
The refresh token is stored as a Secure, HttpOnly cookie for the AuthN server's domain. The client is expected to include it as passive authentication on each request. Is it possible that the PWA could interfere with that transmission?

Cookie implementation: https://github.com/keratin/authn-server/blob/b2b9bdaea5b19c143aca8df02aef61e7e183d7af/server/sessions/util.go#L27

**Comment by drevets** [comment]
**Is it possible that the PWA could interfere with that transmission?** 
Yes, potentially. I've done some searching today and didn't find anything that was a slam dunk that would indicate that this was definitely the problem. I've deployed a little toy app to test out just cookies in a more isolated environment and hopefully that will give me more information tomorrow. 

**Or maybe it's a question of storage permanence and the token is lost during some kind of inactivity GC.**
Also a possibility -- I'm not very familiar with app lifecycles, so it's possible that something happens while the app is suspended/backgrounded that would make it lose data when it's recalled. Like with the cookie issue above, I didn't find anything that would indicate this is a slam dunk (yet). 

It's also totally possible that the cookies and mobile nature of this are red herrings and that the problem is something else. Going to keep on debugging and see if I can find anything relevant -- will post an update.

**Comment by drevets** [comment]
A few updates on this: 

* I believe this is happening when you use our app on any mobile device, not just PWA -- I've also seen the same behavior in Chrome and Safari. 
* The process to recreate the behavior is: a) Log in, b) Use the phone as normal - use other apps (you can either close the browser or background it -- I don't think it matters) c) Open the app the next day (potentially as short at 10 hours later) -- the call to session/refresh will fail and you will be logged out. Expected behavior is that you're logged in for 30 days without needing to log back in (we have not changed any AuthN defaults) 
* I was able to determine that in Safari on iOS, the failing call to /session/refresh is not sent with any cookies. This is potentially the same behavior that is causing this problem across other browsers and devices. 
* I have confirmed that earlier calls to /session/refresh do have the cookie. 

I'm going to look into why the cookies might be disappearing.

**Comment by cainlevy** [comment]
Wow, that's unexpected. Do you ever see successful calls to `/session/refresh` in those environments? If not, maybe there's a cookie configuration issue.

**Comment by drevets** [comment]
I agree, very unexpected! 

And yes, that's (one of the) weird things -- I do see successful calls to `/session/refresh` in those environments. After logging in, I see the response from AuthN with the Set-Cookie header, and then subsequent calls do have the cookie. 

But still, after some (unknown) amount of time, there will be a failing call to `/session/refresh` where the cookie has disappeared. (Assuming that's what's happening in Safari is also what's happening in Chrome and the PWA, which I'm inclined to think it is, given that I was seeing 401s for those `/session/refresh` calls as well). 

I don't know what would happen if I kept my phone open with the app up continuously --- perhaps something is happening when the app is "put to sleep" or when it "wakes up."

**Comment by cainlevy** [comment]
Were you able to discover anything more on this one?

**Comment by drevets** [comment]
Unfortunately I was not ... we weren't able to solve the issue and other things have taken priority.

**Comment by cainlevy** [comment]
Possibly related: https://github.com/keratin/authn-js/pull/55

**Comment by AlexCuse** [comment]
This could definitely be the same thing we have been seeing, not tested on chrome yet but verified same on mobile Firefox this week.  Hoping the explicit expires in the cookie will help, it's hard for me to think of great options beyond that.

**Comment by AlexCuse** [comment]
Ran first overnight test in our staging environment last night and my session seems to stick as I'd expect in Firefox but not safari.  Going to try disabling the tracking protection in safari for next one to see if that could be interfering.

**Comment by AlexCuse** [comment]
> The refresh token is stored as a Secure, HttpOnly cookie for the AuthN server's domain. The client is expected to include it as passive authentication on each request. Is it possible that the PWA could interfere with that transmission? Or maybe it's a question of storage permanence and the token is lost during some kind of inactivity GC.
> 
> 
> 
> Cookie implementation: https://github.com/keratin/authn-server/blob/b2b9bdaea5b19c143aca8df02aef61e7e183d7af/server/sessions/util.go#L27
> 
> 

Looking at this code it seems like offering the same explicit expiry option on the server side could potentially help out too.

**Comment by AlexCuse** [comment]
Ran first overnight test with v1.17 that contains the above PR - it does seem to help at least in our staging environment.  This morning I was still logged in in mobile safari, and appeared logged out in Firefox but got a clean refresh when the site woke up.  I consider both very good signs.

One note is I had safari tracking protection disabled.  Going to turn it back on now.

**Comment by AlexCuse** [comment]
All good overnight again in test environment.  Pushed authn change to production today.  Already hearing some positive response from users to the access token fix hoping this will put it to bed 🤞

**Comment by AlexCuse** [comment]
We have been seeing much better login stickiness in production for a while now I feel like this issue can probably be closed.  Feel free to reopen if not fixed with v1.17 and the `REFRESH_TOKEN_EXPLICIT_EXPIRY` configuration @drevets .  There is a similar setting you can use in the js client if needed that works with the cookie store to do the same thing for access tokens.

**Comment by drevets** [comment]
@AlexCuse this sounds like great progress -- unfortunately I may not get a chance to test out this version in the project that I was working on, but if I do I will comment back with the results of this update.
