### ISSUE TITLE
Forcing the user to re enter credential

### ISSUE THREAD

**Issue by samitc** [keratin/authn-server#206]
Hey,
Is there any option to force the user to re-enter credentials?
I thought maybe resetting all the tokens of the user, but I couldn't find any endpoint that does this. (The endpoint that resets the password does this, but I don't want to reset the password).

**Comment by cainlevy** [comment]
@samitc Are you thinking about a pattern like https://keratin.github.io/authn-server/#/guide-confirm-password, or something different?

**Comment by samitc** [comment]
@cainlevy kind of. I didn't see this option so it does solve my issue, but what I meant is an endpoint that just revoke all user's sessions.

**Comment by cainlevy** [comment]
If you want to accept the next login and then force them to update their password immediately, the expire endpoint may not be quite right. Instead, you may need to read the `password_changed_at` value from https://keratin.github.io/authn-server/#/api?id=get-account and implement custom application logic.

**Comment by samitc** [comment]
Ok, thank for your help
