### ISSUE TITLE
Origin is not a trusted host.

### ISSUE THREAD

**Issue by Raghavsalotra** [keratin/authn-server#21]
I just ran a docker run command mentioned in the documentation and got "Origin is not a trusted host." error.
How can i get rid of this?

**Comment by cainlevy** [comment]
This error is expected when making requests from a frontend that is not whitelisted in the `APP_DOMAINS` var. The docker command probably only lists localhost. Where are you loading the app making requests?

**Comment by Raghavsalotra** [comment]
I am using postman to make requests to authn server.

**Comment by cainlevy** [comment]
Ah, this makes sense! Please try configuring postman to send an Origin header like `http://localhost`.

**Comment by Raghavsalotra** [comment]
Yup it worked.
Steps 
1. Add Origin Header in postman with values "http://localhost:8080"
2. Switch on Postman Interceptor since "Origin" is a restricted header.

**Comment by cainlevy** [comment]
Great!
