### ISSUE TITLE
claims: add amr claim to tokens to indicate MFA status

### ISSUE THREAD

**Issue by AlexCuse** [keratin/authn-server#222]
Looking at the public claims registered maybe something like "Authentication Method Reference" eg `"amr": "totp"` would make sense https://www.iana.org/assignments/jwt/jwt.xhtml

**Comment by AlexCuse** [comment]
Do you think AMR works for this @cainlevy?  Seems close enough to me and fairly easy to document what we're going to send.  Not sure how badly we need this right now, but kinda feel like we should solve before first release that includes MFA.

**Comment by AlexCuse** [comment]
Potential `amr` claim values:

- 'U' (username/password)
- 'T' (token)
- 'O' (oauth)
- 'OTP' (OTP)

So for username/password + MFA we would send `"amr": "U,OTP"`

**Comment by cainlevy** [comment]
Here's a list of values we might use:

https://datatracker.ietf.org/doc/html/rfc8176#section-2
