### ISSUE TITLE
password-less login

### ISSUE THREAD

**Issue by jalberto** [keratin/authn-server#26]
to be able to login with a link would be a great feature

**Comment by jalberto** [comment]
interesting project with similar goals, but focus in passwordless https://github.com/pwdless/cierge

**Comment by etruta** [comment]
Hi all, I'm working in this feature in this branchs:
- authn-server: https://github.com/etruta/authn-server/tree/passwordless
- authn-js: https://github.com/etruta/authn-js/tree/passwordless

This has 2 methods:
1- To request a passwordless token, that send the token to a webhook (responsible to send the email to account id);
2- To login with this token.

@cainlevy, What do you think about this?

**Comment by cainlevy** [comment]
@etruta That looks like thorough work, nicely done! Aside from superficial comments, I only have one serious question: should this token only work once? Feel free to open a PR to discuss further, if you like.

**Comment by etruta** [comment]
@cainlevy This token can be used until expired, your time to expire is setted by env `PasswordlessTokenTTL`. PR created. :)

**Comment by cainlevy** [comment]
Implemented in #71
