### ISSUE TITLE
Fix Migrate task in Makefile

### ISSUE THREAD

**Issue by sathiyaseelan** [keratin/authn-server#35]
The Migrate task is not working, it fails with the below exception.

```
authn-server git:(master) make migrate
go run -ldflags "-X main.VERSION=1.1.0" *.go migrate
go run: cannot run *_test.go files (routing_test.go)
make: *** [migrate] Error 1
```

Have to fix that by individually specifying the files in the Makefile's migrate task.
```go run -ldflags "-X main.VERSION=$(VERSION)" main.go routing.go migrate```

**Comment by cainlevy** [comment]
Thanks! Fixed in https://github.com/keratin/authn-server/commit/0165071d89ed911029eb69dc89ff1b3d60a145db.
