### ISSUE TITLE
Key/value attributes on user/account

### ISSUE THREAD

**Issue by nmenglund** [keratin/authn-server#36]
Hi, would storing key/value pairs on the user be within scope of the project? I might be able to skip having a separate user store in the application altogether if I'm able to store arbitrary data with the user.

**Comment by cainlevy** [comment]
Good question! I'm currently considering this out of scope for a few reasons:

1) Doing it properly would mean finding a way to also encode validations for the extra values
2) AuthN would become a microservice dependency for any rendering path that requires something as simple as a user's name. For example, rendering a list of comments would require N calls to AuthN to fetch each commenter's name (or an optimized endpoint to fetch N names at once).
3) My experience with user tables is that they frequently become god models. Breaking out account concerns seems like a good way to vertically partition the data. I think it's a better architecture.
