### ISSUE TITLE
Custom SQLite db path

### ISSUE THREAD

**Issue by akhedrane** [keratin/authn-server#42]
Why is the db path fixed within current binary path?

https://github.com/keratin/authn-server/blob/d20f79cbdcd317e0cb2d80a3476b4901ed3af87e/data/sqlite3/db.go#L15

**Comment by cainlevy** [comment]
Fixed path is not intended!

The `env string` variable is poorly named and probably left over from an older iteration. In practice, it may be a longer path relative to the current binary:

https://github.com/keratin/authn-server/blob/d20f79cbdcd317e0cb2d80a3476b4901ed3af87e/data/data.go#L15-L18

I'd happily consider pull requests that improve it.

**Comment by akhedrane** [comment]
I think removing the "**./**" to allow use of full path like "**c:/user/full/path/to/db**"
