### ISSUE TITLE
password/reset is returning `404 page not found`

### ISSUE THREAD

**Issue by ken5scal** [keratin/authn-server#45]
Using postman, I generated a request `GET /password/reset?username=kengo` to reset username by following [the document](https://github.com/keratin/authn-server/blob/master/docs/api.md#request-password-reset); however server always returns `404 page not found`.

I am using Postman

**Comment by cainlevy** [comment]
@ken5scal I'd wager that you haven't configured [`APP_PASSWORD_RESET_URL`](https://github.com/keratin/authn-server/blob/master/docs/config.md#app_password_reset_url).

I'm going to leave this issue open until the docs clarify that requirement.

**Comment by ken5scal** [comment]
@cainlevy thanks for your reply!

I run the docker container w/ following arguments including `APP_PASSWORD_RESET_URL`. It is different from the document by its port number.

```
% docker run -it --rm --publish 3000:3000 -e AUTHN_URL=localhost:3000 -e APP_DOMAINS=localhost -e DATABASE_URL=sqlite3:db/demo.sqlite3 -e SECRET_KEY_BASE='my-authn-test-secret' -e HTTP_AUTH_USERNAME=hello -e HTTP_AUTH_PASSWORD=world -e APP_PASSWORD_RESET_URL=http://localhost:3000/password/reset --name authn_app keratin/authn-server:latest sh -c "./authn migrate && ./authn server"
```

Now, from Postman, I was capable of doing `GET localhost:3000/password/reset?username={{user_1}}`, and the server returned 200. However, the webhook which were sent internally seems to fail as the following log suggests. Any thoughts?

```
[2018-03-06 16:16:22.4251886 +0000 UTC m=+163.278531001][GET /password/reset?username=kengo] Webhook: PostForm: Status Code: 405
```

**Comment by cainlevy** [comment]
@ken5scal oh i think i see the problem! authn is sending a `POST` request (`PostForm`) but your application on `localhost:3000` appears to be expecting `GET`.

**Comment by cainlevy** [comment]
I think the updates to https://github.com/keratin/authn-server/blob/master/docs/api.md#request-password-reset and https://github.com/keratin/authn-server/blob/master/docs/guide-implementing_forgotten_passwords.md should help.

**Comment by ken5scal** [comment]
@cainlevy Thanks! I will give a try. Also, this OSS is awesome. If any minor help is needed, please let me have a chance contributing :)
