### ISSUE TITLE
backend to backend communication

### ISSUE THREAD

**Issue by k1ng440** [keratin/authn-server#48]
Please add 
* tcp
* rabbitmq
* nats

**Comment by cainlevy** [comment]
This has potential. RabbitMQ and NATS best practices are outside of my expertise, though, so this is unlikely to proceed without help.

To clarify:

* TCP is the current implementation, yes?
* This would affect both inbound (internal endpoints) and outbound (webhook) communication?

**Comment by k1ng440** [comment]
I think GRPC would be enough for backend communication.

**Comment by cainlevy** [comment]
Closing in favor of #78
