### ISSUE TITLE
make the server plugin-able  

### ISSUE THREAD

**Issue by k1ng440** [keratin/authn-server#49]
Please make the server plugin-able so we add easily add emailer, backend to backend communication and so on.

**Comment by k1ng440** [comment]
see https://github.com/micro/go-micro

**Comment by cainlevy** [comment]
I would recommend tackling those things as one or more sidecar microservices. I'm committed to making that possible with any necessary webhooks.

The primary architectural decision behind AuthN is a hard separation between the authentication code that every app needs and the business code that developers write day-by-day. When those are mixed into the same app, it weakens the security of the authentication layer. Every bug in business code becomes a potential accounts/passwords vulnerability.

AuthN is like a credit card vault, but for passwords and accounts.
