### ISSUE TITLE
It would be nice to see this in awesome-go

### ISSUE THREAD

**Issue by k1ng440** [keratin/authn-server#55]
As the title states, it would be nice to see this listen on https://github.com/avelino/awesome-go to make it more discoverable.

**Comment by ernsheong** [comment]
Opened https://github.com/avelino/awesome-go/pull/2025, but coverage of this repo probably needs upping first.

**Comment by cainlevy** [comment]
I agree! However it seems that awesome-go is intended more for golang libraries than for services written in golang. For example, it has documentation requirements that make sense if the packages are part of the project's API but do not make sense when they are purely internal.
