### ISSUE TITLE
session storage with PostgreSQL

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [keratin/authn-server#61]
I am running with the following error while connecting authn-server to my postgresql docker instance.

_panic: NewRefreshTokenStore: unsupported driver: postgres_

**Comment by roychowdhuryrohit-dev** [comment]
I have found the source of the issue in NewRefreshTokenStore.go

`func NewRefreshTokenStore(db *sqlx.DB, redis *redis.Client, reporter ops.ErrorReporter, ttl time.Duration) (RefreshTokenStore, error) {
	if redis != nil {
		return &dataRedis.RefreshTokenStore{
			Client: redis,
			TTL:    ttl,
		}, nil
	}

	switch db.DriverName() {
	case "sqlite3":
		store := &sqlite3.RefreshTokenStore{
			DB:  db,
			TTL: ttl,
		}
		store.Clean(reporter)
		return store, nil
	default:
		return nil, fmt.Errorf("unsupported driver: %v", db.DriverName())
	}
}`

There's no support for Postgresql. Instead it only supports SQLite and Redis. Please help !

**Comment by cainlevy** [comment]
Happy to reconsider if there's reason to prefer PostgreSQL over Redis.
