### ISSUE TITLE
published documentation 

### ISSUE THREAD

**Issue by k1ng440** [keratin/authn-server#62]
Please use docute, it reads the markdown files and shows them in a nice and readable web page

https://github.com/leptosia/docute
https://gohugo.io/

**Comment by cainlevy** [comment]
This looks like a convenient way to publish the existing docs, thanks for the link!

I got a little demo working, but will need to configure the sidebar and consider revising a few files so they look reasonable in both contexts.

**Comment by cainlevy** [comment]
Opted for docsify to get something started: https://keratin.github.io/authn-server

Once I fix up the landing page I can close this issue!

**Comment by k1ng440** [comment]
I think Hugo with learn theme would be better. 

https://learn.netlify.com/en/

**Comment by cainlevy** [comment]
This seems like a good milestone for now: https://keratin.github.io/authn-server/

Please open new issues if you find the docs are missing something.
