### ISSUE TITLE
AuthN behind cloudflare

### ISSUE THREAD

**Issue by nicholasjackson** [keratin/authn-server#63]
Hi there, 

I have been trying to implement OAuth2 with Github however my I am getting an error from Cloudflare which is sitting in front of my public IP address.  I can see the request hitting the AuthN server in the logs however something strange seems to be happening when It attempts to redirect back to the homepage.

My current settings are that I am running on kubernetes, authn traffic is routed on the path /auth and everything works fine for normal logins and signups but I am not having a great deal of success with OAuth.  I will take cloudflare out of the picture tomorrow to see if I can get things up and running with plain DNS.

Kind regards,

Nic

```
Error 1000 Ray ID: 46754461f5f09b1a • 2018-10-10 01:20:54 UTC
DNS points to prohibited IP
What happened?

You've requested a page on a website (xn--emjify-4v74e.ws) that is on the Cloudflare network. Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system.
What can I do?

If you are the owner of this website:
you should login to Cloudflare and change the DNS A records for xn--emjify-4v74e.ws to resolve to a different IP address.
```

**Comment by nicholasjackson** [comment]
Actually looking at this I am wondering if the server is just doing endless redirects, removing coudflare seems to time out the request

**Comment by cainlevy** [comment]
Do you see anything interesting in your browser's network activity tab?

**Comment by nicholasjackson** [comment]
Hi thanks for the help, I think my reverse proxy was doing something strange, I have replaced this with NGinx and now the redirect is nearly working, I get a success from Authn just figuring out how to handle the session reload in my frontend, I think I am missing a cookie which is probably more Nginx config.

I am planning on a couple of project with AuthN, the first is a demo I am setting up for my company HashiCorp, which integrates a simple app with our stack and K8s.  I am also planning on using Keratin as part of an example I am building for the second edition of my book "Building Microservices with Go" ,  hopefully going to use the same demo.

The demo can be found here, https://xn--emjify-4v74e.ws/ hopefully will have github auth working today, next challenge is to integrate a profile service.

Kind regards,

Nic

**Comment by nicholasjackson** [comment]
Ok getting there now, I have the flow coming back, getting the cookie from authn, just got to fish this out of the browser on redirect.  There were all kinds of weird going on with my reverse proxy.

**Comment by cainlevy** [comment]
@nicholasjackson thanks for the update! let me know if you think of something keratin authn might have done to help debug the situation.

**Comment by cainlevy** [comment]
if it's helpful, here's how i solved for the oauth return trip in my demo app: https://github.com/keratin/authn-demo/blob/master/views/register.erb
