### ISSUE TITLE
CORS issue with same-origin deployment

### ISSUE THREAD

**Issue by nicholasjackson** [keratin/authn-server#67]
Hi,

If running authn-server in k8s behind an ingress which has the following path based routing:
/auth -> authn
/         -> website

When a user logs into the site a CORS error will be returned as since the domain is the same for the post the browser will not send an `Origin` header or attempt pre-flight.

I read the previous comment about disabling CORS and agree that it should be in place however I am wondering if there is a fix for same domain hosted applications.

**Comment by nicholasjackson** [comment]
In this instance would it be safe to fall back to checking the Referer against the Domains?

If the browser does detect a different domain it will preflight and should the Access-Control-Allowed-Origins response header does not contain the correct subdomain it will not send the request.

Fall back to referer would allow domain checking on the same host behind a proxy like Nginx

**Comment by cainlevy** [comment]
I don't have a satisfactory answer here. I'm stuck on three issues:

1. **Referer spoofing** - Can a (modern) browser perform CSRF attacks with a spoofed referer? Apparently it was [possible in Edge as of March 2017](https://www.brokenbrowser.com/referer-spoofing-patch-bypass/).

2. **Referer suppression** - How many users might be lost by requiring the header to exist? According to http://seclab.stanford.edu/websec/csrf/csrf.pdf it's on the order of 0.05-0.22% over HTTPS, but that data is ten years old.

3. **Detecting same-origin requests** - Is it possible to identify a same-origin request, like with the absence of an `Origin` header? I usually have to spend a solid day with CORS, preflights, and CSRF vectors when I want to answer a question like this.

**Comment by cainlevy** [comment]
Might be able to rely on Origin (option 3), if not now then soon:

> For example, Firefox doesn't include an Origin header on same-origin requests. But Chrome and Safari include an Origin header on same-origin POST/PUT/DELETE requests (same-origin GET requests will not have an Origin header).

https://www.html5rocks.com/en/tutorials/cors/

Which leads to a 10-years in the making Firefox patch:

> The Access-Control spec [1] adds an 'Origin' header that is submitted with all requests. I propose that we specify that `<form>` POSTs should do the same.

https://bugzilla.mozilla.org/show_bug.cgi?id=446344
https://bugzilla.mozilla.org/show_bug.cgi?id=446344

**Comment by nicholasjackson** [comment]
That is a good call, however if Origin takes precidence, then I think it will be ok, for example, XHR will always do a preflight to a different domain even if Referrer is present.  I was using Firefox, let me see if I can force it to send origin, it would be better to update the JS framework so that firefox always sends this header local domain or not.

**Comment by silasdavis** [comment]
From what I have read this sounds fine to me and I have implemented in #105.
