### ISSUE TITLE
How can i connect and inspect the databases content with some gui like navicat?

### ISSUE THREAD

**Issue by triesa** [keratin/authn-server#72]
I have sat the authn-server with docker-compose like in example- how can i inspect content with navicat? I tryed to connect but the connection fails to mysql /redis?

**Comment by cainlevy** [comment]
@triesa Which docker command or docker compose configuration did you run?

Here's a bit about connecting Navicat (or another GUI) to MySQL in Docker: https://stackoverflow.com/questions/41374555/how-to-connect-mysql-client-with-server-running-in-docker

**Comment by triesa** [comment]
@cainlevy i have just tried this default one from example [https://github.com/keratin/authn-server/blob/master/docs/guide-deploying_with_docker.md](https://github.com/keratin/authn-server/blob/master/docs/guide-deploying_with_docker.md)

**Comment by cainlevy** [comment]
Try connecting to:

* Host: `127.0.0.1`
* Port: `3306`
* User: `root`
