### ISSUE TITLE
Can i store some additional user data, not only email/username?

### ISSUE THREAD

**Issue by triesa** [keratin/authn-server#73]
Why in this example [https://github.com/keratin/authn-server/blob/master/docs/guide-deploying_with_docker.md](https://github.com/keratin/authn-server/blob/master/docs/guide-deploying_with_docker.md) docker-compose uses redis and mysql, but there is no description in docs, how to add additional user info fields? 

Also is there some build in things for ACL?

**Comment by cainlevy** [comment]
AuthN focuses on authentication only. It's intended to work alongside your application, where you can have a users table and decide on the ACL that's best for you.

My preferred setup is to have a `users` table in my application with an `account_id` field that contains values generated by AuthN. My User model contains all of my business logic, while the Account model (owned by AuthN) handles the session security.

**Comment by triesa** [comment]
@cainlevy thank you. Can you please, explain, what is in redis and what is in mysql?
Do you duplicate values from authn( from mysql in authn? ) inside your application database?
For example : 
every time i perform requests with client - i got from decoded token object with fields like this:
```
{ aud, auth_time, exp, iat, iss, sub }
```

as i understand the user info id is inside  the `sub` field - is it right? Because i cant find this in the documentation, or where is it explained?

So as i understand what you do is :
 1 - get the info from authn by the `sub`/ID 
2 - storing this info inside you user table inside `account_id` - but the meaningfull info from authn - is only `email` and `username` fields- right?

And everytime, when you got request from client- you can find the user from users collection with appropriate `account_id` - and check that users ROLE , decide allow or deny access ? (ACL)

**Comment by cainlevy** [comment]
@triesa You're on the right track! Most of the token fields exist for verification purposes, but the `sub` field is an ID that I prefer to save in `users.account_id`.

> And everytime, when you got request from client- you can find the user from users collection with appropriate account_id - and check that users ROLE , decide allow or deny access ? (ACL)

Yep!

Here's a simple integration for Ruby on Rails:

```ruby
class ApplicationController
  private

  def logged_in?
    !! current_account_id
  end

  def current_user
    return @current_user if defined? @current_user
    @current_user = User.find_by_account_id(current_account_id)
  end

  def current_account_id
    # if your authn-js client is configured to use localstorage then `cookies[:authn]` will need
    # to be replaced by something else like a HTTP Authorization header.
    Keratin::AuthN.subject_from(cookies[:authn])
  end
end
```

> Because i cant find this in the documentation, or where is it explained?

Sorry about that. I'm working on publishing the docs and I will make sure this is covered. 👍

**Comment by cainlevy** [comment]
Updated docs: https://keratin.github.io/authn-server/#/

I'd enjoy hearing if the Introduction there might have helped you when getting started.

**Comment by triesa** [comment]
@cainlevy Awesome! Thank you! Can you also please describe why there is redis and mysql together? What is inside redis and what is inside mysql?

**Comment by Mohammed90** [comment]
MySQL contains the users accounts data (ID, username, password, etc.). Redis contains the tokens.
