### ISSUE TITLE
 'Origin is not a trusted host.'  when performing signup from backend 

### ISSUE THREAD

**Issue by triesa** [keratin/authn-server#76]
How can i signup user from my backend ?
```
response is  'Origin is not a trusted host.' 
 Error: Request failed with status code 403
```
When i do POST request to /accounts with `username` and `password` i get error. 

Also which url should i use to perform signup from backend `AUTHN_URL`? 
Or same as i do from browser?

for example now getting the user from my backend is working like 
` http://HTTP_AUTH_USERNAME:HTTP_AUTH_PASSWORD@authn:3000/accounts/${userId} `
but performing POST for signup from backend caused error

**Comment by Mohammed90** [comment]
Browsers set the Origin header automatically on requests. I had the same issue when I was integrating AuthN into my application backend, and resolved it by setting the Origin header on the HTTP requests.

Heads up: don't forget the refresh tokens. They come-and-go in the cookies.

**Comment by triesa** [comment]
@Mohammed90 which backend do you use? can you please provide example? Which Origin header should i set? 

Did not understand the refresh tokens part here? How to deal with refresh tokens in this case?

**Comment by Mohammed90** [comment]
You'll use the same URL you use on the browser. You just need to set the 'Origin' header on the HTTP request from your backend to AuthN to fool AuthN into thinking it's coming from a browser. Not sure if this is the optimal solution, but this is how I solved anyways. If you're using Go, the code will look roughly something like this:

```go
data := url.Values{
	"username": {username},
	"password": {password},
}

req, _ := http.NewRequest("POST", accountsURL.String(), strings.NewReader(data.Encode()))

req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
req.Header.Set("Origin", c.origin)
```

As for the tokens, AuthN provides the session token in the response body, but the refresh token comes in the cookies part of the HTTP response from AuthN. If your backend will also be responsible for refreshing the sessions, make sure you copy the refresh token as part of the request's cookies.

**Comment by cainlevy** [comment]
The easiest way to integrate AuthN is with a frontend client like https://github.com/Keratin/authn-js. This allows you to send passwords directly to AuthN without routing them through your backend. 

The goal is to treat passwords like credit card numbers. If your backend never "sees" them, you don't have to worry about accidentally exposing them.

An example of what you don't want: https://blog.twitter.com/official/en_us/topics/company/2018/keeping-your-account-secure.html

**Comment by cainlevy** [comment]
@Mohammed90 I may not understand your deployment well enough to answer the question. Could you tell me a bit more about how your situation requires a mediator? Feel free to hop in https://gitter.im/keratin/authn-server and send me messages there if you'd rather not do it here.

@triesa If I understand your issue, you may be wanting to create some accounts in AuthN for users that are not present. There's an [import endpoint](https://keratin.github.io/authn-server/#/api.md?id=import-account) for legacy system migrations that may help your use case. It's available in the [authn-rb](https://github.com/keratin/authn-rb/#other) backend client, but not yet in the authn-go backend client.

**Comment by cainlevy** [comment]
Closing in favor of #79 (a TODO for documentation) and #78
