### ISSUE TITLE
 is there a way to find the user in authn not by id. Can i find the user by email or username? If i know only email?

### ISSUE THREAD

**Issue by triesa** [keratin/authn-server#77]
For example in case if i dont know the authn mysql user id- how can i get it?

Is there a way- how can i get the user from auth if i know only the email or username ?

**Comment by cainlevy** [comment]
Can you help me understand the use case a bit better? When do you know an email/username but not a user, and what will the AuthN account information help you accomplish?

**Comment by triesa** [comment]
@cainlevy i have registered users without saving the authn id for user  inside users table in basical app database. 

Now i need to check if the user already registered in authn. I can try to create ( signup user ) if it fails - i will know that this email already exists in authn - but i cant know that user id from authn to attach the authn_id to users schema in my app.

Also, how can i remove this user from authn or update without knowing the id?

**Comment by cainlevy** [comment]
@triesa Hmm, in this case the accounts import endpoint is not going to help. My suggesting is connecting to the AuthN database and fetching a list of `[id, email]`, then using that to fill in the gaps in your main database.

If this situation was expected in normal operation, I would need to add a new endpoint. Please post back if the suggested approach does not work.
