### ISSUE TITLE
convert to gRPC with REST proxy

### ISSUE THREAD

**Issue by cainlevy** [keratin/authn-server#78]
AuthN could support both gRPC and REST by converting the core service to gRPC and integrating https://github.com/grpc-ecosystem/grpc-gateway. This could make it easier to write backend clients in target languages while maintaining flexibility for frontend clients that don't want to bundle grpc-web (50kb).

**Comment by dhillondeep** [comment]
Any updated on this? I can potentially look at this if no one else is working on this!

**Comment by dhillondeep** [comment]
After some discussion it was decided that it is best to have a GRPC fork for this and you can check the fork at https://github.com/uptimize/authn-grpc
