### ISSUE TITLE
show correct ip address when deployed behind proxy

### ISSUE THREAD

**Issue by cainlevy** [keratin/authn-server#8]
The IP address printed in request logs is from `req.RemoteAddr`. But when authn-server is deployed behind a proxy (e.g. load balancer) the correct address is more commonly found in `X-Forwarded-For`.

But we only want to parse `X-Forwarded-For` when the server is behind a proxy. We can do this by enabling a config option that adds gorilla.ProxyHeaders to the middleware stack.

**Comment by egorsmkv** [comment]
Maybe, that library -- https://github.com/tomasen/realip -- helps you where the same problem already solved.

**Comment by cainlevy** [comment]
That looks like a nice single-purpose library. In this case, I think [gorilla.ProxyHeaders](https://godoc.org/github.com/gorilla/handlers#ProxyHeaders) will be easier because it allows AuthN to continue using gorilla.CombinedLoggingHandler.
