### ISSUE TITLE
Restriction of password recovery attempts?

### ISSUE THREAD

**Issue by triesa** [keratin/authn-server#81]
Will something like this be implemented?

**Comment by cainlevy** [comment]
What manner of restriction? Rate limiting?

**Comment by triesa** [comment]
yes, rate limiting, or there can be some other manners?

**Comment by triesa** [comment]
i have encountered that some times, i dont know why, but authn server sends too many results on the `APP_PASSWORD_RESET_URL` the url which receives info that pass resettted, an will email the user.

I dont know why it happens.  But i know it happens without the calling to `password/reset`. 

Also, why [https://github.com/keratin/authn-js/blob/e8a53ee9899e50b1b27aa11ff9a63fcc3b317b2f/src/api.ts#L71](https://github.com/keratin/authn-js/blob/e8a53ee9899e50b1b27aa11ff9a63fcc3b317b2f/src/api.ts#L71)  here is performed `get` request , why not post ? Its like there is some changes assumes and seens that `post` should be performed ?Or it does not matter?

**Comment by cainlevy** [comment]
rate limiting is definitely on my list!

> authn server sends too many results on the APP_PASSWORD_RESET_URL

I wonder if you're noticing AuthN's retry mechanism. What status code are you returning to AuthN when it calls that URL? It is supposed to stop sending notifications for any response with a 200-299 status code.

**Comment by againksy** [comment]
I just did not return anything =)

With 200 it seems all okey. Not tried any other statuses

**Comment by cainlevy** [comment]
i've opened #82 to improve the documentation on this next time i'm taking a pass through the guides
