### ISSUE TITLE
FieldErrors#Error: Extra Commas in Message

### ISSUE THREAD

**Issue by Mohammed90** [keratin/authn-server#89]
This particular line has a bug:
https://github.com/keratin/authn-server/blob/cea0f445cfb7949bc9c6db6127023e52af1f622d/app/services/validations.go#L35

The slice is created with length equal to the number of fields errors, but then the values are appended instead of being assigned to the empty cells of the slice. This means the first half of `FieldErrors` is always empty, and all the errors are in the latter half. The lines 34 to 36 should be changed to:
```go
	for i, e := range es {
		buf[i]  = e.String()
	}
```

**Comment by Mohammed90** [comment]
I've fixed it on my end and will be included along with gRPC patches.

**Comment by cainlevy** [comment]
😅
