### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by frewsxcv** [keratin/authn-server#9]
This looks like a cool project, nice work! ✨ 

I was reading the README and noticed it's mentioned as being GPL, though it looks like there's and LGPL license in the project root. Might be good to clarify which license it is, I can open a PR for that if you want 💁‍♂️

**Comment by cainlevy** [comment]
Ahh, good spot!

I think the LICENSE file wins, so updating the README makes the most sense. I'd happily accept that PR.

Here's to hoping that licensing never comes back to haunt ... 🙈
